FROM rust:1.55
WORKDIR /usr/src/myapp

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./

RUN mkdir ./src && \
    touch ./src/lib.rs && \
    cargo build

COPY . .

CMD ["cargo", "watch", "-i", "front", "-x", "run"]
