FROM rust:1.55 as chef
WORKDIR /app

RUN cargo install cargo-chef

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS runtime 
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

RUN cargo install cargo-watch

COPY . .

CMD ["cargo", "watch", "-i", "front", "-x", "run"]
