"use client";

import { GoogleAuthProvider, signInWithRedirect } from 'firebase/auth';
import Head from 'next/head';
import { useRouter } from 'next/navigation';
import { useContext, useEffect } from 'react';
import { AuthContext } from '../../context/auth';
import { auth } from '../../utils/firebase';
import styles from './index.module.css';

export default function Signin() {
  const router = useRouter()
  const { currentUser } = useContext(AuthContext)

  useEffect(() => {
    if (!currentUser) return
    router.push('/create-user')
  }, [currentUser])

  const login = () => {
    const provider = new GoogleAuthProvider()
    signInWithRedirect(auth, provider)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={login}>googleでログインする</button>
      </main>
    </div>
  )
}
