import Head from "next/head";
import React from "react";
import { Header } from "../components/Header";
import { MeView } from "../components/MeView";

export default function Me() {
  return (
    <div className="m-0">
      <Head>
        <title>Alp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen m-0 flex flex-col overflow-hidden">
        <Header className="flex-initial" />

        <div className="h-1 flex-none bg-gray-200"></div>

        <MeView></MeView>
      </main>
    </div>
  );
}
