import firebase from 'firebase'
import Router from 'next/router'
import Head from 'next/head'
import { useContext, useEffect } from 'react'
import { AuthContext } from '../context/auth'
import styles from '../styles/Home.module.css'

export default function Signin() {
  const { currentUser } = useContext(AuthContext)

  useEffect(() => {
    currentUser && Router.push('/')
  }, [currentUser])

  const login = () => {
    const provider = new firebase.auth.GoogleAuthProvider()
    firebase.auth().signInWithRedirect(provider)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={login}>googleでログインする</button>
      </main>
    </div>
  )
}
