schema: 'http://localhost:8000'
documents: pages/**/*.graphql
extensions:
  codegen:
    generates:
      ./graphql.schema.json:
        plugins:
          - introspection
      generated/graphql.tsx:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
    overwrite: true
